# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  true
        formats: { json: true, xml: false, rss: false }
    serializer:
        serialize_null: true

